-- UNION serve para juntar os registros de duas ou mais tabelas

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES; -- 12
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES; -- 5

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION -- Retorna a união dos registros da coluna "BAIRRO" da tabela de clientes e de fornecedores
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION ALL -- Retorna a união, incluindo as duplicações
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES;
