-- Script para criar as tabelas de clientes e produtos do 0, já implementando a chave primária:
USE SUCOS_VENDAS;

DROP TABLE TABELA_DE_CLIENTES;

CREATE TABLE TABELA_DE_CLIENTES(
	CPF CHAR(11) NOT NULL, -- NOT NULL pois irá receber a chave primária já na criação da tabela
	NOME VARCHAR(100) NULL,
	ENDERECO1 VARCHAR(150) NULL,
	ENDERECO2 VARCHAR(150) NULL,
	BAIRRO VARCHAR(50) NULL,
	CIDADE VARCHAR(50) NULL,
	ESTADO VARCHAR(2) NULL,
	CEP CHAR(8) NULL,
	DATA_DE_NASCIMENTO DATE NULL,
	IDADE SMALLINT NULL,
	GENERO CHAR(1) NULL,
	LIMITE_DE_CREDITO MONEY NULL,
	VOLUME_DE_COMPRA FLOAT NULL,
	PRIMEIRA_COMPRA BIT NULL,
CONSTRAINT PK_CLIENTES PRIMARY KEY CLUSTERED(CPF));

DROP TABLE TABELA_DE_PRODUTOS;

CREATE TABLE TABELA_DE_PRODUTOS(
	CODIGO_DO_PRODUTO VARCHAR(10) NOT NULL,
	NOME_DO_PRODUTO VARCHAR(50) NULL,
	EMBALAGEM VARCHAR(20) NULL,
	TAMANHO VARCHAR(10) NULL,
	SABOR VARCHAR(20) NULL,
	PRECO_DE_LISTA SMALLMONEY NULL,
CONSTRAINT PK_PRODUTOS PRIMARY KEY CLUSTERED(CODIGO_DO_PRODUTO));

